### PR TITLE
Move Onboarding to app-level

### PR DESCRIPTION
**Pull request by ualch9**
- Onboarding now occurs before the root controller is initialized, replacing Bulletin.
- Moves onboarding responsibility from `OBAKit` → `App` (i.e. OneBusAway app).

First-time users can now grant a one-time location authorization for `Automatically select region`. This permission is independent from a formal location authorization, so it doesn't count against our location permission usage.

# Video
(In the video, the recording is dimmed while the location system prompt is presented)

https://user-images.githubusercontent.com/22162410/216621367-4e8fa531-babb-444f-b993-0064cda03b18.mov

### CODE REVIEW

**Comment by ualch9** [comment]
`KiedyBus` needs the region picker page, but does it need the migration page?

@aaronbrethorst 
cc @wkulesza

**Comment by ualch9** [comment]
Created wiki pages:
- https://github.com/OneBusAway/onebusaway-ios/wiki/Get-Started
- https://github.com/OneBusAway/onebusaway-ios/wiki/White-Label
- https://github.com/OneBusAway/onebusaway-ios/wiki/White-Label-Onboarding

GitHub will host images and has inline Mermaid graph support (nice-looking graphs that are easy to maintain).

**Review by aaronbrethorst — APPROVED** [review]
👍

**Comment by aaronbrethorst** [comment]
docs look great, @ualch9. thanks for writing them up

**Pull request merged**
